name = "Roman admin"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
build = "npm run build:admin"
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec react-router dev"
