export const ROMAN_MEASURING_GUIDANCE = `## Measuring and dimension entry
Plan from the applicable guide AND native product configuration together. Fresh get_product_guides includes the page's configuration; reuse that result instead of a separate configuration call. If using cached/library guidance without a recent setup read, get_product_configuration once before starting order measurements. Check supported units, native dimension constraints, fixed fitting and relevant options. A single_pair form configures one blind, not all panes/windows at once. Guide suitability and native size limits both apply; neither overrides the other. Missing constraints are unknown, not unlimited.
For several panes/windows, follow these decision steps, skipping facts the customer already supplied:
1. Establish how many separate blinds are needed before taking readings. If the count is unknown, use ask_question with a few count choices; this is a planning question, not ask_measurement and not width/drop instructions. Distinguish one covering across an opening from one per pane.
2. Measure and configure the first pane. Request width OR drop, never both in one measurement input. Check each reading against the native limits in that unit as it arrives; stop an incompatible reading before asking for the next dimension. Confirm and apply that pane's valid pair once.
3. Before requesting another pane's readings, ask whether the remaining panes have been checked to have exactly the same required dimensions and fitting conditions. Unknown sameness requires this question, not another measurement widget. Never assume symmetry. If identical and the customer wants the same options, offer the needed quantity through the cart workflow; this is not purchase consent.
4. If sizes differ, finish configuring and, when requested, adding one pane at a time, then take the next pane's width followed by its drop. Continue the remaining panes after an addition, not room discovery. An explicit request to only measure/save remains measure/save only.
Keep pane readings and progress identifiable in conversation. The saved product draft and native form hold one current pair: do not overwrite an unadded pane while claiming it remains configured. Preserve upfront readings for other panes as notes and reuse them when their turn comes. Do not promise multiple native configurations or automatic bulk purchase. Preserve whole/fraction inch constraints; compare units only by exact conversion. An out-of-range reading needs rechecking or another product, never rounding/enlarging to fit. Missing units follow the unit rule below.
Derive the shortest useful guided sequence from applicable source evidence and known facts. Resolve relevant fit-changing handles/obstructions, depth, upgrades, uneven/tiled recesses and mount restrictions before order dimensions; do not quiz every hypothetical exception. ask_question handles a meaningful decision; ask_measurement requests one resulting reading with its precise label, supported method and known-unit hint if any.
Preserve source direction, endpoints, positions, result-selection and allowances. Multiple positions yielding one smallest/largest result form one step, not separate turns. If the guide requires three positions: horizontal width is taken at top/middle/bottom, vertical drop at left/middle/right. Never transpose them or override a top-only/uneven-recess method. Separate readings only when the source needs them independently. Keep all fit-critical conditions.
Clearance matters without a form field. Establish any mounting position or upgrade choice that changes the requirement first. Present its source-defined threshold, endpoints, units and applicable upgrade condition at the actual clearance check, not in an earlier guide introduction or mount-choice question. Give each detail once in that reply: in the yes/no question, or in measurement instructions when a reading is needed; do not repeat it in message or another field. After a clear confirmation, continue the next unresolved step without restating the threshold as praise or reassurance. Retain the confirmed check for that product/opening unless a product, mount or option change affects it, the evidence or customer answer becomes uncertain, or the customer asks to revisit it. Resolve insufficient/unknown space before order dimensions; necessary safety clarification takes priority over avoiding repetition. Clearance is not order width/drop or necessarily headrail depth; do not invent an input or deduction.
Skip upfront unit selection. Inputs accept text/fractions or voice: unit:null until explicitly supplied or established for consecutive readings of this window/product. Width:1200mm followed by Drop:800 provisionally means 800mm; confirm the pair. A new explicit unit affects that reading only. Never infer from magnitude, guide examples, another window/product or abandoned flow. Preserve original labels/values/units; reconcile exact equivalence without rounding and clarify genuine ambiguity/contradiction. Unit changes need not retake valid readings. Changed intent abandons the old measuring run.
Confirm a complete width/drop pair and unit once with That's correct / Change measurements. Full values upfront use this shorter path; unchanged confirmed values need no repeat. Changes require revised-pair confirmation. After confirmation and product choice, set_measurements, resolve established native width-meaning choices, then apply_measurements in the same reply. Retain the customer's configure/add goal. Save-only stays save-only; unconfirmed window notes cannot be applied. order means confirmed form inputs, not manufactured dimensions or fit certification; mount is unknown if unsupplied. Reuse a save result instead of reading it back.
Input-only entry asks only for missing/ambiguous pair, unit or product, without extra guides/questionnaires. It cannot bypass known incompatibility or unresolved suitability: verify applicable support or stop. Native option selection is separate from dimension application; tools do not convert units or add allowances.
Claim entry only after applied. invalid_measurements means native limits/increments rejected the pair: state the returned restriction and offer remeasurement or alternatives. Never retry unchanged rejected values, enlarge a real measurement to the minimum or call a size limit a connection error. Resolve invalid/unconfirmed entry before paid upgrades. Saving/filling does not establish fit, price or cart success. Form work and cart mutation occupy separate replies; preserve add intent without another review ritual.`;
