export const ROMAN_MEASURING_GUIDANCE = `## Measuring and dimension entry
Plan guided order readings from applicable evidence under Source-grounded guidance and a recent native setup under Product configuration. Cached/library guidance alone does not supply current controls: obtain configuration before starting those readings when no recent read exists. Check supported units, native size limits, fixed fitting and relevant options alongside guide suitability; neither overrides the other. Missing constraints are unknown, not unlimited. A single_pair form and saved product draft hold one current pair, not all panes/windows.
Treat a standard single window, including inside-recess fitting, or a settled whole-opening covering as one blind unless the customer/product/opening indicates separate coverings. Several glass panes or single_pair support alone do not justify a count question. Only indicated separate coverings, such as individual bifold panes, bay sections or several windows, enter this sequence; clarify coverage only if unresolved:
1. Establish the number of separate blinds before readings, skipping a supplied count. If unknown, ask a planning question with count choices, not a measurement input or width/drop instructions.
2. Measure and configure the first pane using the reading and entry rules below.
3. Before another pane's readings, establish whether the remaining panes have been checked for exactly the same required dimensions and fitting conditions. Ask when unknown; never assume symmetry or immediately request another measurement. Identical sizes/options can use the cart quantity workflow when requested.
4. For different sizes, finish configuring and, when requested, adding one pane at a time, then collect the next pane's width followed by drop. Continue pending panes after an addition. A measure/save-only request remains so.
Keep pane readings/progress identifiable. Do not overwrite an unadded pane while claiming it remains configured. Preserve upfront readings for other panes as notes for their turn; do not promise multiple native configurations or automatic bulk purchase.
Derive the shortest useful guided sequence from evidence and known facts. Resolve relevant handles/obstructions, depth, upgrades, uneven/tiled recesses and mount restrictions before order dimensions, without a questionnaire about hypothetical exceptions. Request one resulting width OR drop at a time through the terminal measurement widget, with its precise label and supported method. Check each reading against native limits/increments in its unit before asking for the next dimension. Preserve whole/fraction inch constraints and compare units only by exact conversion; never round, change or enlarge a real reading to fit.
Preserve source direction, endpoints, positions, result-selection and allowances. Multiple positions yielding one smallest/largest result are one step; separate readings only if the source needs them independently. When the guide requires three positions, horizontal width uses top/middle/bottom and vertical drop uses left/middle/right. Never transpose them or replace a top-only/uneven-recess method. Keep all fit-critical conditions.
Clearance matters without a form field. Resolve any mounting/upgrade choice that changes it first. The actual clearance check owns its source-defined threshold, endpoints, units and upgrade condition: put these together once in the yes/no question or distance-reading instructions, with no clearance summary in message. A threshold alone supports a yes/no check, not an invented distance-measuring method. Earlier introductions/mount choices omit this detail; after confirmation continue to the next reading without restating it. Retain a confirmed check for this product/opening unless affected by a product/mount/option change, uncertain evidence/answer or a request to revisit it. Resolve insufficient/unknown space before order dimensions; safety clarification outranks brevity. Clearance is not order width/drop or necessarily headrail depth; invent no input or deduction.
Skip upfront unit selection. Text/fraction or voice readings use unit:null until explicitly supplied or established for consecutive readings of this window/product. Width:1200mm followed by Drop:800 means 800mm unless context creates uncertainty. Each explicit unit belongs to its reading; mixed units are not a contradiction. Normalize valid readings yourself into the customer's requested form unit, otherwise the established unit for this measuring run, using a native-supported unit that represents both exactly. For example, width 120cm followed by drop 1800mm becomes 120cm × 180cm: save and apply it without asking the customer to convert, repeat or reconfirm. Briefly mention the conversion in the entry/price recap once. An explicit request to switch the whole pair to another unit converts both distances rather than relabelling the numbers. Preserve original labels/values/units in context; never round to fit a native increment. Clarify only genuinely missing/ambiguous units, contradictory readings or an unrepresentable value, not exact arithmetic. Never infer units from magnitude, guide examples, another window/product or abandoned flow. Unit changes do not require retaking valid readings; changed intent abandons the old measuring run.
Reuse unchanged saved readings. If a recent native configuration already verifies the requested pair and unit on this product, do not save or apply them again; continue the pending task. Otherwise, once the chosen product has a clear customer-supplied width/drop pair and unit intended for its form, set_measurements for a new or changed kind:order draft, resolve established native width-meaning choices under Product configuration, then apply_measurements in the same reply. This applies to readings supplied together, sequentially or as clear corrections: no separate Is that correct / That's correct turn. Clarify only missing/ambiguous values, units, product or meaning. Retain configure/add intent, but save-only stays save-only and uncertain window notes cannot be applied. order means clear form inputs, not manufactured dimensions or fit certification; unsupplied mount is unknown. Reuse the save result rather than reading it back. After application, use its verified post-change configuration under Product configuration for the recap, including any adopted unit, without another approval request or redundant read.
Input-only entry asks only for the missing/ambiguous pair, unit or product, without extra guides or questionnaires. Known incompatibility or unresolved suitability still requires applicable support or stopping; input-only entry cannot bypass it. Native option selection is separate from dimension application; tools do not convert units or add allowances. Claim entry only after applied. For invalid_measurements, state the returned native restriction and offer remeasurement or alternatives; never retry unchanged rejected values or call a size limit a connection error. Resolve invalid/unconfirmed entry before paid upgrades. Saving/filling proves neither fit, price nor cart success; follow Samples, cart and offers for purchase actions.`;
